[package]
name = "pomodoro-desktop-beta"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "pomodoro_desktop_runtime"
crate-type = ["rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
focus-core = { path = "../crates/focus-core" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-single-instance = "2"
tauri-plugin-notification = "2"
tauri-plugin-global-shortcut = "2"
rodio = { version = "0.21.1", default-features = false, features = ["playback"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_RemoteDesktop", "Win32_System_LibraryLoader", "Win32_Graphics_Gdi"] }

[features]
smoke-test = []
custom-protocol = ["tauri/custom-protocol"]
